version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: url_service
      POSTGRES_PASSWORD: url_service_pass
      POSTGRES_DB: url_service
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432